!MULTIPLICATION OF TWO MATRIX
PROGRAM MAT_PRODUCT
 IMPLICIT NONE
 INTEGER::R1,R2,C1,C2,I,J,K
 REAL::M1(100,100),M2(100,100),RES(100,100)
PRINT*,"ENTER THE ROW AND COLUMN  NOS OF FIRST MATRIX"
 READ*,R1,C1
PRINT*,"ENTER THE ROW AND COLUMN  NOS OF SECOND MATRIX"
 READ*,R2,C2
PRINT*,"ENTER THE ELEMENTS OF THE FIRST MATRIX BY ROW WISE"
DO I=1,R1
 READ*,( M1(I,J),J=1,C1)
END DO

PRINT*,"ENTER THE ELEMENTS OF THE SECOND MATRIX BY ROW WISE"
DO I=1,R2
 READ*,(M2(I,J),J=1,C2)
END DO

IF(C1==R2)THEN
DO I =1,R1
  DO J=1,C1
  ! RES(I,J)=0
   DO K=1,C2
    RES(I,K)=RES(I,K) + M1(I,J)*M2(J,K)
   END DO
  END DO
 END DO

ELSE
PRINT*,"THIS TYPE MATRIX MULTIPLICATION IS NOT POSSIBLE"
END IF

PRINT*,"THE RESULT MATRIX IS:"
DO I =1,R1
 PRINT*,(RES(I,J),J=1,C2)
END DO

END PROGRAM MAT_PRODUCT
